@baseUrl = http://localhost:8090

@genreId =0b3251c1-09fc-4e24-a8e7-2b0538cd9e21
@movieId =f28b97ff-44c7-465e-9d68-09bd3d17964c


POST  http://localhost:8080/admin/sample-data
####
POST  http://localhost:8081/admin/sample-data
############################################
### 0. GET All Genres (GET)
### Expected: 200 OK
############################################
GET {{baseUrl}}/genres


############################################
### 1. CREATE Genre (POST)
### Expected: 201 Created
############################################
POST {{baseUrl}}/genres
Content-Type: application/json

{
  "name": "mystery",
  "description": "Whodunit thrillers"
}


############################################
### 2. GET All Genres (GET)
### Expected: 200 OK
############################################
GET {{baseUrl}}/genres


############################################
### 3. GET Single Genre by ID (GET /{id})
### Expected: 200 OK
############################################
GET {{baseUrl}}/genres/{{genreId}}


############################################
### 4. CREATE Movie inside Genre (POST)
### Expected: 201 Created
### If genre does NOT exist → 404 Not Found
############################################
POST {{baseUrl}}/genres/{{genreId}}/movies
Content-Type: application/json

{
  "title": "New Movie",
  "releaseYear": 2005,
  "rating": 9.1
}


############################################
### 5. GET All Movies from Genre (GET)
### Expected: 200 OK
### If genre exists but empty → []
### If genre does not exist → 404 Not Found
############################################
GET {{baseUrl}}/genres/{{genreId}}/movies


############################################
### 6. UPDATE Movie (PUT /{movieId})
### Expected: 204 No Content
### If movie or genre missing → 404 Not Found
############################################
PUT {{baseUrl}}/genres/{{genreId}}/movies/{{movieId}}
Content-Type: application/json

{
  "title": "New Movie Reloaded",
  "releaseYear": 2011,
  "rating": 9.2
}


############################################
### 7. DELETE Movie (DELETE /{movieId})
### Expected: 204 No Content
############################################
DELETE {{baseUrl}}/genres/{{genreId}}/movies/{{movieId}}


############################################
### 8. DELETE Genre (DELETE /{genreId})
### Cascade delete all movies
### Expected: 204 No Content
############################################
DELETE {{baseUrl}}/genres/{{genreId}}


############################################
### 9. GET All Genres with Movies
### Expected: 200 OK
############################################
GET {{baseUrl}}/genres/with-movies
